### PR TITLE
Fix AMP compatibility

### PR DESCRIPTION
**Pull request by westonruter**
- [x] Fix paths to Genericons font files in Primer parent theme, as per https://github.com/godaddy/wp-lyrical-theme/pull/64.
- [x] Prevent enqueueing `stout-hero.js` in AMP.
- [ ] Figure out way to refactor `.hero` to avoid needing `stout-hero.js`.
- [ ] Figure out why `#masthead` appears with a gap at the top when admin bar is shown in AMP.

### CODE REVIEW

**Comment by westonruter** [comment]
@EvanHerman I'm going to leave this with you. Perhaps you can address the two other items?

**Comment by EvanHerman** [comment]
@westonruter Sure I can take a look at resolving those two. Thanks for this PR 👍

**Comment by EvanHerman** [comment]
@westonruter Just a follow up - this is still on our radar. We're just working on getting a few things out the door before I loop back around to finish this up.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival

**Pull request closed without merging**
